/**
 * Signologos — useSignDetection hook.
 *
 * Integrates MediaPipe Hands + TensorFlow.js for real-time ASL detection.
 * Used by the SIGNER role while their camera is active.
 *
 * Flow:
 * 1. MediaPipe extracts 21 hand landmarks per frame
 * 2. Landmarks are normalized to 63 features (21 × x,y,z)
 * 3. TensorFlow.js classifier predicts the ASL letter
 * 4. Letters are buffered with debounce logic
 * 5. When camera turns off, accumulated text is returned
 */

import { useRef, useState, useCallback, useEffect } from 'react';
import * as tf from '@tensorflow/tfjs';
import { SIGN_DETECTION, ASL_LABELS } from '../utils/constants';

interface UseSignDetectionReturn {
    currentLetter: string;
    currentConfidence: number;
    accumulatedText: string;
    isModelReady: boolean;
    modelLoadingProgress: string;
    error: string | null;
    startDetection: (videoElement: HTMLVideoElement) => void;
    stopDetection: () => string;
    resetText: () => void;
}

export function useSignDetection(): UseSignDetectionReturn {
    const modelRef = useRef<tf.LayersModel | null>(null);
    const handDetectorRef = useRef<any>(null);
    const animFrameRef = useRef<number | null>(null);
    const isRunningRef = useRef(false);
    const bufferRef = useRef<string[]>([]);
    const accumulatedRef = useRef('');
    const lastConfirmedRef = useRef('');
    const lastConfirmedTimeRef = useRef(0);

    const [currentLetter, setCurrentLetter] = useState('');
    const [currentConfidence, setCurrentConfidence] = useState(0);
    const [accumulatedText, setAccumulatedText] = useState('');
    const [isModelReady, setIsModelReady] = useState(false);
    const [modelLoadingProgress, setModelLoadingProgress] = useState('');
    const [error, setError] = useState<string | null>(null);

    // Load models on mount
    useEffect(() => {
        let cancelled = false;

        async function loadModels() {
            try {
                setModelLoadingProgress('Loading TensorFlow.js...');
                await tf.ready();

                setModelLoadingProgress('Loading sign language model...');

                // Try to load the trained model
                try {
                    const model = await tf.loadLayersModel('/models/sign_classifier/model.json');
                    modelRef.current = model;
                    console.log('[SignDetection] Model loaded successfully');
                } catch {
                    console.warn('[SignDetection] Trained model not found. Detection will use placeholder logic.');
                    // In development, we'll work without the model
                    // The model.json needs to be generated by the ML pipeline (Phase 4)
                }

                setModelLoadingProgress('Loading MediaPipe Hands...');

                // Load MediaPipe Hands
                try {
                    const vision = await import('@mediapipe/tasks-vision');
                    const { HandLandmarker, FilesetResolver } = vision;

                    const filesetResolver = await FilesetResolver.forVisionTasks(
                        'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm'
                    );

                    const handLandmarker = await HandLandmarker.createFromOptions(filesetResolver, {
                        baseOptions: {
                            modelAssetPath: 'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',
                            delegate: 'GPU',
                        },
                        runningMode: 'VIDEO',
                        numHands: 1,
                        minHandDetectionConfidence: 0.5,
                        minTrackingConfidence: 0.5,
                    });

                    handDetectorRef.current = handLandmarker;
                    console.log('[SignDetection] MediaPipe Hands loaded');
                } catch (err) {
                    console.warn('[SignDetection] MediaPipe load error:', err);
                }

                if (!cancelled) {
                    setIsModelReady(true);
                    setModelLoadingProgress('');
                }
            } catch (err) {
                if (!cancelled) {
                    setError(`Failed to load AI models: ${err}`);
                    setModelLoadingProgress('');
                }
            }
        }

        loadModels();

        return () => {
            cancelled = true;
        };
    }, []);

    const normalizeLandmarks = useCallback((landmarks: any[]): number[] => {
        // Extract x, y, z for all 21 landmarks
        const coords: number[] = [];
        for (const lm of landmarks) {
            coords.push(lm.x, lm.y, lm.z);
        }

        // Normalize relative to bounding box
        const xs = landmarks.map((lm: any) => lm.x);
        const ys = landmarks.map((lm: any) => lm.y);
        const minX = Math.min(...xs);
        const maxX = Math.max(...xs);
        const minY = Math.min(...ys);
        const maxY = Math.max(...ys);
        const rangeX = maxX - minX || 1;
        const rangeY = maxY - minY || 1;

        const normalized: number[] = [];
        for (const lm of landmarks) {
            normalized.push(
                (lm.x - minX) / rangeX,
                (lm.y - minY) / rangeY,
                lm.z
            );
        }

        return normalized;
    }, []);

    const classifyLandmarks = useCallback(
        async (landmarks: number[]): Promise<{ letter: string; confidence: number } | null> => {
            if (!modelRef.current) return null;

            return tf.tidy(() => {
                const input = tf.tensor2d([landmarks], [1, 63]);
                const prediction = modelRef.current!.predict(input) as tf.Tensor;
                const probabilities = prediction.dataSync();
                const maxIndex = probabilities.indexOf(Math.max(...Array.from(probabilities)));
                const confidence = probabilities[maxIndex];
                const letter = ASL_LABELS[maxIndex] || '?';

                return { letter, confidence };
            });
        },
        []
    );

    const processBuffer = useCallback((letter: string, confidence: number) => {
        const now = Date.now();

        // Don't process NOTHING predictions
        if (letter === 'NOTHING') {
            bufferRef.current = [];
            return;
        }

        // Add to buffer
        bufferRef.current.push(letter);

        // Keep buffer size manageable
        if (bufferRef.current.length > SIGN_DETECTION.CONFIRMATION_FRAMES * 2) {
            bufferRef.current = bufferRef.current.slice(-SIGN_DETECTION.CONFIRMATION_FRAMES);
        }

        // Check if we have enough consecutive same letters
        const recentLetters = bufferRef.current.slice(-SIGN_DETECTION.CONFIRMATION_FRAMES);
        const allSame = recentLetters.length >= SIGN_DETECTION.CONFIRMATION_FRAMES &&
            recentLetters.every((l) => l === letter);

        if (allSame && confidence >= SIGN_DETECTION.CONFIDENCE_THRESHOLD) {
            // Debounce: don't add same letter too quickly
            if (
                letter !== lastConfirmedRef.current ||
                now - lastConfirmedTimeRef.current > SIGN_DETECTION.DEBOUNCE_MS
            ) {
                // Confirm the letter
                if (letter === 'SPACE') {
                    accumulatedRef.current += ' ';
                } else if (letter === 'DEL') {
                    accumulatedRef.current = accumulatedRef.current.slice(0, -1);
                } else {
                    accumulatedRef.current += letter;
                }

                setAccumulatedText(accumulatedRef.current);
                lastConfirmedRef.current = letter;
                lastConfirmedTimeRef.current = now;
                bufferRef.current = [];
            }
        }
    }, []);

    const detectionLoop = useCallback(
        (videoElement: HTMLVideoElement) => {
            if (!isRunningRef.current) return;

            const handLandmarker = handDetectorRef.current;

            if (handLandmarker && videoElement.readyState >= 2) {
                try {
                    const results = handLandmarker.detectForVideo(videoElement, performance.now());

                    if (results.landmarks && results.landmarks.length > 0) {
                        const landmarks = results.landmarks[0];
                        const normalized = normalizeLandmarks(landmarks);

                        // Classify using the model
                        classifyLandmarks(normalized).then((result) => {
                            if (result) {
                                setCurrentLetter(result.letter);
                                setCurrentConfidence(result.confidence);
                                processBuffer(result.letter, result.confidence);
                            }
                        });
                    } else {
                        setCurrentLetter('');
                        setCurrentConfidence(0);
                    }
                } catch (err) {
                    // Silently handle detection errors (common during transitions)
                }
            }

            // Schedule next frame (at target FPS)
            const delay = 1000 / SIGN_DETECTION.TARGET_FPS;
            setTimeout(() => {
                animFrameRef.current = requestAnimationFrame(() => detectionLoop(videoElement));
            }, delay);
        },
        [normalizeLandmarks, classifyLandmarks, processBuffer]
    );

    const startDetection = useCallback(
        (videoElement: HTMLVideoElement) => {
            if (!isModelReady) {
                console.warn('[SignDetection] Models not ready yet');
                return;
            }

            isRunningRef.current = true;
            accumulatedRef.current = '';
            bufferRef.current = [];
            setAccumulatedText('');
            setCurrentLetter('');

            animFrameRef.current = requestAnimationFrame(() => detectionLoop(videoElement));
            console.log('[SignDetection] Detection started');
        },
        [isModelReady, detectionLoop]
    );

    const stopDetection = useCallback((): string => {
        isRunningRef.current = false;

        if (animFrameRef.current) {
            cancelAnimationFrame(animFrameRef.current);
            animFrameRef.current = null;
        }

        const result = accumulatedRef.current.trim();
        setCurrentLetter('');
        setCurrentConfidence(0);

        console.log(`[SignDetection] Detection stopped. Text: "${result}"`);
        return result;
    }, []);

    const resetText = useCallback(() => {
        accumulatedRef.current = '';
        bufferRef.current = [];
        setAccumulatedText('');
    }, []);

    // Cleanup on unmount
    useEffect(() => {
        return () => {
            isRunningRef.current = false;
            if (animFrameRef.current) {
                cancelAnimationFrame(animFrameRef.current);
            }
        };
    }, []);

    return {
        currentLetter,
        currentConfidence,
        accumulatedText,
        isModelReady,
        modelLoadingProgress,
        error,
        startDetection,
        stopDetection,
        resetText,
    };
}
